### ISSUE TITLE
today_kwh incorrectly calculated?

### ISSUE THREAD

**Issue by eliotlandrum** [pywemo/pywemo#126]
I believe that today's kWh is being incorrectly calculated in this function, but wanted to run it by @pavoni before doing a PR.

 https://github.com/pavoni/pywemo/blob/1cae67c15a80cf9806187e9cd0a75ffe7e19b7fa/pywemo/ouimeaux_device/insight.py#L70

I believe it should be more like this:

```
   kw_today = self.insight_params['todaymw'] / 1000000 # from mw to kw
   time_today = selft.insight_params['ontoday'] / 3600 # from seconds to hours

   return kw_today * time_today
```

**Comment by pavoni** [comment]
All these things are reverse engineered - so it's a matter of trying to work out what makes sense.

We picked the current calculation up from ouimeaux before we forked.

I guess the way to find out is to leave a device on for a known period - and check how the calculation matches a common sense version.

Would welcome a PR - particularly if you can include the details of your investigation.

Looking at the HA wrapper we don't currently return this - which I'd guess is because the current value didn't make sense to me at the time.

**Comment by eliotlandrum** [comment]
Ok, good to know. Thinking about grabbing a Kill A Watt to compare with.

**Comment by sqldiablo** [comment]
@eliotlandrum, please let me know if I can help in any way, although my focus right now is on a pretty big set of changes to make rediscovery better.

**Comment by eliotlandrum** [comment]
Thanks, @sqldiablo ! I have a Kill A Watt on order, hopefully will have some numbers early next week. :) I'm actively working on a little project that uses this, so would like some good numbers to come out.

**Comment by eliotlandrum** [comment]
I've been running the Kill A Watt all day on my stereo and the numbers are matching correctly for the existing `today_kwh`, so however it's doing this.. it works already!
