### ISSUE TITLE
Async API for pywemo?

### ISSUE THREAD

**Issue by sullivanmj** [pywemo/pywemo#151]
Has there ever been any discussion about adding an async API for pywemo? It would be nice to have from a client's perspective. There are several challenges that that would need to be overcome. The two biggest challenges apparent to me are:

- ouimeaux does not have an async API. Of course this could be overcome by modifying the code within this repository, but it could make absorbing any future changes to ouimeaux costly
- disruption to existing clients, unless the existing API is also kept and maintained

Of course, with a solid design, the impact of these and other obstacles could be minimized.

For what it's worth, I created a proof of concept for this in the [async branch of my fork of pywemo](https://github.com/sullivanmj/pywemo/tree/async). Specifically, what I did was to make the `discovery.discover_devices` call async. the `ouimeaux.Device._reconnect_with_device_by_discovery` method has not been updated, and it would fail. Please note that my background in programming is almost exclusively C#, so I might not have done things in a very pythonic way :).

An async API is something that I would be happy to contribute to, if that would make a difference in deciding whether or not to implement this. With all of this said, I understand if async is not the direction that you want to go with this repository.

**Comment by sqldiablo** [comment]
Hey, if you're willing to develop it, I'm willing to code review the PR. ;-)

I don't think async has been much of a priority for us, mainly because Home Assistant is one of the main consumers of this library (and why it exists in the first place), and it wraps the sync calls to pyWeMo in async routines of its own. Any app using pyWeMo could do the same thing.

Like I said above, we're happy to review submissions for changes and merge them in for this. I would just ask that you try to avoid breaking changes as much as possible. Instead, I would recommend introducing new functions/routines for the async stuff and leaving the signatures and behavior of the existing functions/routines intact.

**Comment by sullivanmj** [comment]
Great! Understood. I agree that would be best for existing consumers of pyWeMo, to not make any breaking changes.

Is there a standing approach to dealing with ouimeaux? For example, is it mostly locked in, as-is, with only highly desirable new features and/or bugfixes being added? Or something else? I'm curious, because that might inform my design a little bit.

**Comment by sqldiablo** [comment]
The parts of ouimeaux that we use have been stagnant for years in the original repo. I've made a few changes to it in this repo as necessary, so I don't think we're opposed to modifying it. If there ever is a change to the original version that we would want, we'd probably have to port it manually anyway.

**Comment by sqldiablo** [comment]
Sorry, let me correct myself: we've made extensive changes to the devices in ouimeaux. It's the API within ouimeaux that has only seen minimal changes. With that said, I still don't really have a problem with changing any of it, it would just need to be very thoroughly tested with as many different types of Wemos as possible. I have most of them, and would be willing to help with the testing.

@pavoni, any thoughts on this?

**Comment by pavoni** [comment]
Like @sqldiablo I'm very open to this if you'd like to work on it.

The ouimeaux code was forked long ago - and I don't think maintaining compatibility is really important. The substantial work needed to reverse engineer the devices is the most valuable aspect of the ouimeaux code - and if new devices are added it should be pretty straightforward to port any new devices across even if we diverge further. This low level code has changed very little over the years.

As @sqldiablo says the main user of this library is Home Assistant - and I think it's pretty widely used (I messed up a released a while back - and it caused a lot of pain!) - so I'd want to be cautious about anything that might affect HA. The main difficultly with this code base is testing. It uses undocumented calls in a complex and unreliable environment!

The code was forked from ouimeaux mainly because of the complexity of the ouimeaux async environment - so would be keen to try and keep the environment simple. That said one of the benefits of using Python async is exactly that!  The current event handling thread code is far from elegant - although it has been stable in HA.

So very open to add async if we can do it without risking stability for HA users.

My final thought is that I no longer spend much time on this repo (mainly because it just works) - so I'd be depending on @sqldiablo to review and do the bulk of testing - which fortunately he seems happy to do!

**Comment by sullivanmj** [comment]
Understood. Thanks for all of your input. It all seems reasonable to me. I'll put extra emphasis on keeping the existing public interface intact. It's good to hear that @sqldiablo has a lot of devices. I only have an Insight and some standard switches (for now :)).

Before I dive into this, I had a couple of questions and a possible concern:

1. Is there any automated test suite or general testing strategy for pyWeMo, outside of manual testing?

2. What drives the officially supported version of python for this repository? I noticed that the Travis CI build for pyWeMo uses python 3.5.3. And the project's README indicates that the package is intended for use with python 2. It looks like that might be a deal breaker for the use of the async/await pattern.

**Comment by pavoni** [comment]
Python 2 compatibility used to be a big deal - but I think very few people still depend on it. So personally would be happy to fork the library leaving an older one that supports Python 2. @sqldiablo what do you think?

It would be great to have a proper testing and release regime - but it's quite a bit of work to set up. Would welcome a contribution!

**Comment by sqldiablo** [comment]
@pavoni, let's move the python 2 support discussion to #152 and keep this issue for adding async functionality to pyWeMo.

**Comment by sullivanmj** [comment]
I am happy to add automated tests for any new code that I write. My testing experience in python so far, has been with pytest. I plan on using that, unless someone has a preference for some other test framework.

Since the changes required for this issue will break interoperability with python 2, I intend to do this work in a branch off of the deprecate-python-2 branch.

**Comment by sqldiablo** [comment]
That works for me. We should already be setup for tox/pytest for the most part, we just haven't implemented any tests with it yet. I've been working in the branch you mentioned to get our CI/CD testing process working a little better and to be a little more stringent on the ouimeaux code, which we had been giving a free pass on the tests until now. There are a lot of linting/typing issues with that code, and I'll see if I can get some of it cleaned up a bit.

**Comment by sullivanmj** [comment]
I thought about this project the other day and realized that I had left this issue just dangling. I hate to renege on offering to do something like this, but I don't have the time and don't expect that I will any time soon. Maybe someday I'll find it :)
