### ISSUE TITLE
Some users find device discovery doesn't work

### ISSUE THREAD

**Issue by pavoni** [pywemo/pywemo#23]
A known issue that SSDP discovery doesn't work across subnets - so this could be the issue.

Also perhaps related to http://community.wemothat.com/t5/WEMO-Hardware/UPnP-implementation-incorrect/td-p/13698

Some ideas about using a belkin specific scan here:-
https://objectpartners.com/2014/03/25/a-groovy-time-with-upnp-and-wemo/

and here
http://mattenoble.com/2013/08/07/wemo-hacking/

Just collecting useful contributions. Here is some router setting advice.
http://community.wemothat.com/t5/WEMO-Application/Wemo-switches-undetected-after-half-hour-of-normal-operation/m-p/25482#U25482

**Comment by pavoni** [comment]
Good suggestion from @InsidersByte to just document in the README.

**Comment by pavoni** [comment]
Contribution from @kk7ds that allows device IPs to be configured.

Will add some docs and then close.

**Comment by gitaaronc** [comment]
I had the same trouble..Here is the solution..At least for me.
Update ssdp.py after line 218
and before
        sock.sendto(ssdp_request, ssdp_target)
add this
        sock.bind(('192.168.4.134', 8012))

Replace the ip address in bind. A function could be added to get the interface IP address.

Would be happy to provide a fix if you are to busy.

**Comment by gitaaronc** [comment]
proposal is here now: https://github.com/gitaaronc/pywemo

**Comment by pavoni** [comment]
I'd guess that you have a wemo at 192.168.4.134, so I've added a description of how to use a known ip address to the readme https://github.com/pavoni/pywemo/blob/master/README.md. 

Can you check if that works for you?

**Comment by gitaaronc** [comment]
Hi Greg,

The issue is with the SSDP broadcast and discovery of devices not controlling a device by known IP address.

The IP address of 192.168.4.134 is the IP address of the HomeAssistant server.
Adding socket.bind((‘192.168.4.134’, 0)) to 
pywemo/ssdp.py scan function solves the problem.
Multicast/Broadcast will not work if the socket is not bound to an IP address.
My repo has the updated code required to fix my issue. It includes a function to find the IP address of the local interface.

Take a look at:
https://github.com/gitaaronc/pywemo/blob/master/pywemo/ssdp.py
lines 199 through 271

Thanks,

Aaron

**Comment by jaharkes** [comment]
SSDP discovery is working for me without your changes so there must be something else different about your environment.
- Do you have a firewall that is blocking UDP packets?
- How many network interfaces does your machine have.

Your code will send a discovery for each ip address associated with the local machine and then wait for a full timeout for each one. If this really is a multiple network (/interface) issue, it would be far more efficient to create N sockets, bind them to their respective interface addresses, send all discovery request packets and then start waiting for responses with a select on all sockets.

**Comment by gitaaronc** [comment]
It should only use the first interface. I have nothing blocking requests. Running in a Windows 10 environment.  I haven't tried it on Linux yet, maybe tonight.

**Comment by kk7ds** [comment]
Yeah, I don't understand why the changes have any effect. Locally I see no difference between the existing and changed discovery process. Equally unreliable.

FWIW, I have multiple interfaces and "the first one" wouldn't be sufficient. I control the discovery process out the proper nic right now by making sure I have a proper route out the one that packets need to go to. That's the right way to set it up, IMHO, because otherwise I'd have no way of using discovery if you just bind and use the first interface.

**Comment by gitaaronc** [comment]
Could you try it?

**Comment by jaharkes** [comment]
Trying to figure out if this is a local problem or a problem with how getaddrinfo is used here.
Also you can pass address family as the third argument and not have the extra test in the loop.

```
>>> socket.getaddrinfo('', None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by jaharkes** [comment]
What do you get when you run this from the python command prompt? Because I think the result I get here is the proper address to bind to. When I do not specify the AI_PASSIVE i just get the address of the loopback interface because in that case it returns the address to use for `connect()` and `sendto()` instead of `bind()`.

```
>>> socket.getaddrinfo(None, 0, socket.AF_INET, socket.SOCK_DGRAM, 0, socket.AI_PASSIVE)
[(<AddressFamily.AF_INET: 2>, <SocketType.SOCK_DGRAM: 2>, 17, '', ('0.0.0.0', 0))]
```

To summarize my findings of the use of socket.getaddrinfo
- It lightly wraps around the getaddrinfo system function, and as a result (at least on Linux) does not accept the `''` shortcut which python exposes in socket.bind (and socket.connect?) to indicate INADDR_ANY.
- It normally returns an address to connect to instead of an address to bind to, you have to specify the AI_PASSIVE flag, otherwise you just get the loopback address.
- It should not and cannot be used to discover interface addresses, there is a `netifaces` python modules that exposes that functionality in a cross-platform way.

Most likely your code could be replaced by a single `sock.bind('', 0)` right before the sendto to make sure the socket has a local port allocated to receive the discovery response packets. Maybe Windows 10 needs to have that port explicitly allocated, while Linux automatically assigns one whenever we send something which could explain why discovery is working for me.

**Comment by jaharkes** [comment]
When I edit a comment, does it send out a new email, or is the edit only visible when someone looks at the issue on the github website?

**Comment by gitaaronc** [comment]
It sends a new email. This is a direct reply. I think.
Aaron

Sent from my Samsung device

-------- Original message --------

**Comment by jaharkes** [comment]
On Tue, Mar 29, 2016 at 12:00:56PM -0700, gitaaronc wrote:

> It sends a new email. This is a direct reply. I think.

I'm guessing you may not have seen the actual edited comment because the
one you replied to was a new one.

I wonder if this much smaller patch fixes your discovery issue.

```
diff --git a/pywemo/ssdp.py b/pywemo/ssdp.py
index a45e1c5..9569a39 100644
--- a/pywemo/ssdp.py
+++ b/pywemo/ssdp.py
@@ -216,7 +216,7 @@ def scan(st=None, timeout=DISCOVER_TIMEOUT, max_entries=None, match_mac=None):

     try:
         sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
-
+        sock.bind('', 0)
         sock.sendto(ssdp_request, ssdp_target)

         sock.setblocking(0)
```

**Comment by gitaaronc** [comment]
I tried the above code, it didn't work. No devices were discovered. 
I use wireshark to sniff my network, the broadcast packet is not sent.
The only way broadcast packets are sent on my machine, running Windows 10 64 bit are by binding to an address, either manually setting it or by iterating through the ethernet adapters and addresses and programmatically setting the address used in the bind operation.
Instead of iterating the adapters and addresses I could set the server/binding address in a config file or pass it in on, the command line.

**Comment by jaharkes** [comment]
Did you get an assertion, because it should have been `sock.bind(('', 0))` instead of what I had written in my patch.

**Comment by jaharkes** [comment]
@gitaaronc could you try PR #43.

It is trying to bind to interface addresses in a cross platform way by using the netifaces module to get a list of all interfaces and their associated addresses and then choosing the ones that have a declared broadcast address as potential candidates for discovery requests.

**Comment by pavoni** [comment]
Now we've merged @jaharkes fix - and added the docs about how to work with devices where discovery doesn't work - I'm going to close this.
