### ISSUE TITLE
Long Press Issue for old firmware switches

### ISSUE THREAD

**Issue by CoderBrad** [pywemo/pywemo#353]
I have two Wemo lightswitches (uuid:Lightswitch-1_0) on firmware WeMo_WW_2.00.2263.PVT. These are undetectable in the iOS app after setting up on my network but can be found on the network and respond to setup.xml requests. They had worked with pywemo at one time and, upon further review, it looks like the issue is that 0.7.0 changed these switches to support long press but the firmware my switches are stuck on does not support that firmware. I can fix the issue by altering the code in discovery.py to use:
```
return LightSwitch(location)
```
instead of  the current LightSwitchLongPress. One possible fix might be to use a separate try/catch (which does appear to work in testing by replacing the current line with:
```
            try:
                return LightSwitchLongPress(location)
            except PyWeMoException:
                return LightSwitch(location)
```
Which I would expect to use lightswitch as a fallback but I'm not sure how much overhead that would add or what it might do if the accessory for some reason could not be set up as a LightSwitchLongPress or LightSwitch. I assume it would fall through to the encapsulating try/catch block but Python is not my day-to-day language.

**Comment by esev** [comment]
Hi @CoderBrad, thanks for the report. When you have a moment, could you paste in the stack trace you're getting when it fails?

**Comment by CoderBrad** [comment]
I attached logging and have uploaded the results of running with debug=true to https://pastebin.com/dexyb4rp

**Comment by Spectre5** [comment]
Looks like @CoderBrad's assessment is spot on: `MissingServiceError('Missing required services/methods: rules(StoreRules, FetchRules)')`, which comes from the `LongPressMixin` required services.  If a switch doesn't have it, then indeed it should be fine to use a regular light switch without that mixin.  Just depends on whether @esev wants to handle it with the try/except as suggested or more explicitly.  I think catching the `MissingServiceError` would be more appropriate here, or else create a new exception specifically for the long press mixin.

Either way, it would be good to get a test case (vcr) added for this as part of the fix.  Hopefully CoderBrad can help with that.

**Comment by esev** [comment]
Thank you @CoderBrad!

I'm with you @Spectre5, catching the `MissingServiceError` and going with @CoderBrad's try/except suggestion seems appropriate in this case.

One minor downside is that the number of requests to fetch all the service xml files doubles if we try both.

I was also thinking about trying to parse the firmware version to try to find where support for long press started, but I think the exception handling is much easier.

**Comment by Spectre5** [comment]
Ya, I figured it would be hard to find the firmware version where this changed, but I'd considered that idea too.  But I think a robust handling on whether a device has those two rules may be better.

Good point about doubling the requests to get the services.  Another option may be to make those two rules "optional" instead of required and then have the device activate/deactive that functionality based on the presence of those two rules on initialization.  Or perhaps use some wrapper class or function to determine whether a light switch or long press light switch should be returned.

**Comment by CoderBrad** [comment]
Alternatively could short-term caching be implemented on the urllib3 calls to handle the second calls? There would still be some processing overhead but I'm guessing that would be minimal compared to the calls to the switch.

**Comment by esev** [comment]
Looking at this issue again.. One thing I noticed from the output on pastebin is that this light switch uses `/Lightsetup.xml` instead of `/setup.xml` for the initial device description file. I think that'll work for detecting these. It may also work for some WeMo emulators too.

```patch
diff --git a/pywemo/discovery.py b/pywemo/discovery.py
index b00870c..5db4476 100644
--- a/pywemo/discovery.py
+++ b/pywemo/discovery.py
@@ -81,6 +81,8 @@ def device_from_uuid_and_location(  # noqa: C901
         if uuid.startswith("uuid:Socket"):
             return Switch(location)
         if uuid.startswith("uuid:Lightswitch-1_0"):
+            if not location.endswith("/setup.xml"):
+                return LightSwitch(location)
             return LightSwitchLongPress(location)
         if uuid.startswith("uuid:Lightswitch-2_0"):
             return LightSwitchLongPress(location)
```

I definitely would like to have a test case for this. In [test_lightswitch.py](https://github.com/pywemo/pywemo/blob/main/tests/ouimeaux_device/test_lightswitch.py) it would only require copying one of the existing test cases classes for this device and running the tests. See the [developing section](https://github.com/pywemo/pywemo/tree/main#developing) in README.rst for instructions on setting up a pyWeMo dev environment. Then run `pytest tests/ouimeaux_device/test_lightswitch.py` after activating the venv. That'll produce some files in the `tests/vcr/tests.ouimeaux_device.test_lightswitch` directory that will be used to ensure we don't break support for this device in the future.

Example (change IP address as needed):

```python
class Test_NoLongPress(Base):
    """Tests for the WeMo WeMo_WW_2.00.2263.PVT firmware."""

    @pytest.fixture
    def lightswitch(self, vcr):
        with vcr.use_cassette("WeMo_WW_2.00.2263.PVT"):
            return device_from_uuid_and_location(
                "uuid:Lightswitch-1_0-SERIALNUMBER",
                "http://192.168.1.100:49153/Lightsetup.xml",
            )
```
