### ISSUE TITLE
returned model_name from discovery is not always correct

### ISSUE THREAD

**Issue by danielfaulknor** [pywemo/pywemo#89]
Some Motion switches return XML that has "Switch" as the modelName
The UUID should be used to determine the model name.

**Comment by pavoni** [comment]
If pywemo is creating the correct object we have a few options:-

1.  It would be very easy to add a `model_name` in the `Motion` class to override the base`model_name` method. This could always return `Switch` (or whatever is required). Or call the base function and change sensor to switch - but otherwise just return what it says (might be more future proof).
2. Do the above but always return `Motion` and have HA decide what object to create.
3. Add a new method in both the base and the motion `get_ha_device_type` that returns the HA compatible device type.
4. Change HA to use the wemo class - rather than the model string. I changed this for the other HA device I wrote code for:-
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/vera.py#L111

**Comment by MartinHjelmare** [comment]
My advice would be to at least not add a method or attribute that is specific for home assistant to pywemo. I think keeping the library agnostic to the where it is implemented is a good thing.

If wemo XML returns something, it could be good to keep access to that in some way, so that the original information from the device is not lost.

The next advice would be to let users of the library have an easy way of knowing the intended use of the device. If it's a motion device or if it's a switch device etc. This is what home assistant needs to know. If this is an attribute of a class or the class name itself doesn't matter too much, although the former is perhaps a bit more convenient.

So 1., 2. and 4. sound ok to me. 2. is ok as long as `Motion` is the correct characteristic use of the device.

**Comment by sqldiablo** [comment]
I've ordered one of these devices so I can work on this issue, but it won't arrive until the end of the month. I'll take a look at this in a couple weeks. (Yes, I realize this is a very old issue and that the devices are discontinued, but I'd still like to get this figured out for folks to use)

**Comment by sqldiablo** [comment]
@danielfaulknor, as far as I can tell, this is already working properly. I'm seeing both the UUID and model name of my motion sensor being returned as Sensor, and is getting mapped to the Motion device type. In Home Assistant, this carries across, and the Motion device type is mapped to a binary_sensor, as expected.

A couple questions:

1. Is your WeMo device running the latest firmware?
2. Are you running the latest version of pywemo (0.4.34) and a reasonably recent version of Home Assistant?
3. The Motion + Switch is actually 2 distinct devices, a Sensor device that is the motion sensor, and a Switch device that is the controllable outlet. Each device will have a different IP and will be discovered separately by pywemo and Home Assistant. To be sure I understand your issue correctly, you're specifically talking about the motion sensor itself, and not the switch, correct?

**Comment by sqldiablo** [comment]
Also, the way pywemo maps a device to its device type/class is by the UUID, not by the modelName from the device's setup.xml, so even if the device does report an incorrect modelName, it should still map to a Sensor if the UUID starts with Sensor.

**Comment by sqldiablo** [comment]
Ok, I'm going to apologize here. I just took another look at the Home Assistant code, and I can see how HA would map to the wrong device when the UUID is Sensor, but the modelName is Switch. It turns out that HA is using the model_name to map devices after all. I'm thinking that we should have HA use the class name for mapping instead of the model name from pywemo's device object. I don't like the idea of hard-coding/overwriting what the WeMo device itself is telling us, but as long as pywemo is making the correct kind of device object (Motion in this case), then interrogating the class name of the device object pywemo creates would tell HA more accurately what the device is. I'll do some testing with this, and if it pans out, I'll PR it into HA and close this issue.

**Comment by danielfaulknor** [comment]
I fixed my specific issue in this HA PR, after other changes changed how the model is picked up - https://github.com/home-assistant/home-assistant/pull/15627

To answer your questions:

1 - Yes
2 - Yes
3 - Definitely the motion sensor.

As mentioned, my motion sensor returns "Switch" for modelName in the xml but the UUID is correct

**Comment by sqldiablo** [comment]
Thanks, @danielfaulknor. Just to confirm, this continues to be an issue in HA for you, right? Looking at the code, I would expect HA to identify this device incorrectly. It's a weird course of events that causes it, because pywemo makes the correct motion object based on the UUID, but then HA interrogates the model_name property of that object, sees Switch, and thinks that the Motion object returned by pywemo is actually a Socket device in HA. As stated earlier, I'll PR a fix for this into HA. I'll have HA use the name of the device class returned by pywemo to identify what kind of device it is, instead of using the model_name property. That way it'll rely upon pywemo to make the determination of what kind of device it is (since it's doing the correctly).

**Comment by sqldiablo** [comment]
@danielfaulknor The change for this has been merged into dev in https://github.com/home-assistant/home-assistant. Can you see if it fixes the issue for you?
